import buildingImage from "@/images/building.jpg"; // imports building iamge to use as background

    /* relative         -   allows positioning inside this section
                                                                                                   min-h-screen     - makes it at least full screen height
                                                                                                   overflow-hideen  - hides anything that spills outside */

export default function MFAPage() { // creates React component called MFAPage, "export default" means next.js can use as page
  return (
    <main                                                                                     //overflow-hideen  - hides anything that spills outside
      className="relative flex min-h-screen items-center justify-center overflow-hidden"      // relative         -   allows positioning inside this section
      style={{                                                                                // min-h-screen     - makes it at least full screen height                                                                                        
        backgroundImage: `                                                                    
          linear-gradient(rgba(0, 32, 96, 0.78), rgba(0, 32, 96, 0.82)),                 
          url(${buildingImage.src})                                                           //Top layer: blue transparent overlay,  Bottom layer: building image
        `,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",                                                       //image does not repeat/tile
      }}
    >
      {/* MFA Card */}
      <section className="w-full max-w-5xl rounded-3xl bg-white px-16 py-14 shadow-2xl">    // creates white box in the middle
                                                                                            // wf-full - takes full available width
        {/* Logo */}                                                                        //max-w-5x1 - but does not exceed a large fixed max width 
        <h1 className="mb-14 text-6xl font-extrabold tracking-tight text-black">            
          OKC PARTNERS                                                                      // creates logo using text then makes it big bold and black                                                                                            
        </h1>                                                                               

        {/* Heading */}
        <h2 className="mb-4 text-5xl font-bold text-slate-900">
          Enter verification code
        </h2>

        {/* Description */}
        <p className="mb-12 text-2xl text-slate-500">
          We sent a 6-digit code to your authenticator app.
        </p>

        {/* OTP Inputs */}
        <div className="mb-12 flex gap-6">
          {Array.from({ length: 6 }).map((_, index) => (                           // Array.from({ length: 6}) - creates an array with 6 items
            <input                                                                 // .map((_, index) => ( - loops through 6 items and creates 1 <input> each time generated by React, sintead of manyally writing 6 inputs
              key={index}
              type="text"
              maxLength={1}
              className="h-28 w-28 rounded-2xl border border-slate-300 text-center text-5xl font-semibold text-slate-900 outline-none transition focus:border-blue-600 focus:ring-4 focus:ring-blue-200"
            />
          ))}
        </div>

        {/* Button */}
        <button className="w-full rounded-2xl bg-blue-600 py-6 text-2xl font-semibold text-white transition hover:bg-blue-700">
          Verify and continue
        </button>
      </section>
    </main>
  );
}     



