// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// `dotenv/config` only reads `.env`, which this project does not have — the
// connection strings live in `.env.local` (what Next.js reads at runtime).
// Without this the CLI sees no DATABASE_URL/DIRECT_URL and every command fails
// with "The datasource.url property is required in your Prisma config file".
import { config } from "dotenv";
config({ path: [".env.local", ".env"] });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The CLI (migrate/db push) must use the session-mode pooler; the
    // transaction-mode pooler in DATABASE_URL is for the app at runtime.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
